import 'package:flutter/material.dart';
import 'package:sixam_mart/util/app_constants.dart';

ThemeData light({Color color = const Color(0xFFFF6A00)}) => ThemeData(
  fontFamily: AppConstants.fontFamily,
  primaryColor: color,
  secondaryHeaderColor: const Color(0xFFFF8F1F),
  disabledColor: const Color(0xFF9F9F9F),
  brightness: Brightness.light,
  hintColor: const Color(0xFF9F9F9F),
  cardColor: Colors.white,
  scaffoldBackgroundColor: const Color(0xFFFFF6F0),
  shadowColor: Colors.black.withValues(alpha: 0.06),
  iconTheme: IconThemeData(color: color),
  primaryIconTheme: IconThemeData(color: color),
  appBarTheme: const AppBarTheme(
    backgroundColor: Color(0xFFFFF6F0),
    foregroundColor: Color(0xFF1A1C1E),
    surfaceTintColor: Colors.transparent,
    elevation: 0,
  ),
  textButtonTheme: TextButtonThemeData(style: TextButton.styleFrom(foregroundColor: color)),
  colorScheme: ColorScheme.light(
    primary: color,
    secondary: const Color(0xFFFF8F1F),
    surface: const Color(0xFFFFF6F0),
    error: const Color(0xFFFF3B30),
  ),
  popupMenuTheme: const PopupMenuThemeData(color: Colors.white, surfaceTintColor: Colors.white),
  dialogTheme: const DialogThemeData(surfaceTintColor: Colors.white, backgroundColor: Colors.white),
  floatingActionButtonTheme: FloatingActionButtonThemeData(
    backgroundColor: color,
    foregroundColor: Colors.white,
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(500)),
  ),
  bottomAppBarTheme: const BottomAppBarThemeData(
    color: Colors.white,
    surfaceTintColor: Colors.white,
    height: 60,
    padding: EdgeInsets.symmetric(vertical: 5),
  ),
  dividerTheme: const DividerThemeData(thickness: 0.2, color: Color(0xFFDDE1E6)),
  tabBarTheme: const TabBarThemeData(dividerColor: Colors.transparent),
);

const Map<String, Color> buttonBackgroundColorMap ={
  'pending': Color(0x29FF6A00),
  'accepted': Color(0x2EFF8F1F),
  'ongoing': Color(0x2EFF8F1F),
  'completed': Color(0x5faff4c1),
  'settled': Color(0x6e93b347),
  'canceled': Color(0x2EFF3B30),
  'approved': Color(0x80356e4c),
  'expired' : Color(0x8C7C3B3B),
  'running' : Color(0x793c4fd8),
  'denied':  Color(0x2EFF3B30),
  'paused': Color(0xff0461A5),
  'resumed' : Color(0x6f2f5e41),
  'resume' : Color(0x8e387c54),
  'subscription_purchase' : Color(0x3cecc98d),
  'subscription_renew' : Color(0x1d6bf5a2),
  'subscription_shift' : Color(0x452599ee),
  'subscription_refund' : Color(0x1dc97eee),
};

const Map<String, Color> buttonTextColorMap ={
  'pending': Color(0xffff6a00),
  'accepted': Color(0xffff8f1f),
  'ongoing': Color(0xffff8f1f),
  'completed': Color(0xff03b158),
  'settled': Color(0xf57b9826),
  'canceled': Color(0xffff3b30),
  'approved': Color(0xff16B559),
  'expired' : Color(0xff9ca8af),
  'running' : Color(0xff707ec6),
  'denied':  Color(0xffff3b30),
  'paused': Color(0xff0461A5),
  'resumed' : Color(0xff16B559),
  'resume' : Color(0xff16B559),
  'subscription_purchase' : Color(0xffe7680a),
  'subscription_renew' : Color(0xff16B559),
  'subscription_shift' : Color(0xff0461A5),
  'subscription_refund' : Color(0xffba4af8),
};
